module Page
  module User
    module SnsCredentialRegistrations
      class NewPageComponent < ApplicationComponent
        @form: untyped

        @create_sns_credential_registration_path: untyped

        @html_options: untyped
      end
    end
  end
end
