# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
Bundler/OrderedGems:
  Enabled: true

# Enforce consistent parameter indentation
Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# rbs-inline の型コメント用で不要と判断。特に他のコメントに関してもスペースの有無は拘りないので一括disable
Layout/LeadingCommentSpace:
  Enabled: false
