module Domain
  module User
    class EmailConfirmationFormComponent < ApplicationComponent
      @form: untyped

      @confirmation_path: untyped

      @resource_name: untyped

      def initialize: (form: untyped, confirmation_path: untyped, resource_name: untyped) -> void
    end
  end
end
