module Domain
  module User
    class LoginFormComponent < ApplicationComponent
      @resource: untyped

      @resource_name: untyped

      @login_path: untyped

      def initialize: (resource: untyped, resource_name: untyped, login_path: untyped) -> void
    end
  end
end
