module Domain
  module User
    class SnsCredentialRegistrationFormComponent < ApplicationComponent
      @form: untyped

      @create_sns_credential_registration_path: untyped

      def initialize: (form: untyped, create_sns_credential_registration_path: untyped) -> void
    end
  end
end
