class User::SnsCredential::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  @user: untyped

  def google_oauth2: () -> untyped

  def failure: () -> untyped

  private

  def callback_for: (untyped provider) -> untyped
end
