---
name: mini_magick
version: '5.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 8c8db1451cc30c65cfec77dbdabf6e6bbc115d01
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
