class User::EmailConfirmationForm
  include ActiveModel::Model

  include ActiveModel::Attributes

  include ActiveModel::Validations::Callbacks

  def model_name: () -> untyped

  def call: () -> (false | untyped)

  private

  def trim_email: () -> untyped
end
