class User::SnsCredentialRegistrationForm
  @user: untyped

  @pending_credential: untyped

  include ActiveModel::Model

  include ActiveModel::Attributes

  attr_reader user: untyped

  attr_reader pending_credential: untyped

  def model_name: () -> untyped

  def email: () -> untyped

  def provider: () -> untyped

  def call: () -> (false | untyped)

  private

  def validate_token: () -> (nil | untyped)

  def validate_user: () -> (nil | untyped)
end
