---
name: json-jwt
version: '1.16'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: d07edeb13c53de1c65b2bede98a720ac52d497a2
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
