module Ui
  module Button
    class IconComponent < ApplicationComponent
      @category: untyped

      @size: untyped

      @type: untyped

      @variant: untyped

      @text: untyped

      @icon: untyped

      @icon_position: untyped

      @style: untyped

      @html_options: untyped
    end
  end
end
