module Page
  module User
    module DatabaseAuthentications
      class NewPageComponent < ApplicationComponent
        @form: untyped

        @create_database_authentication_path: untyped
      end
    end
  end
end
