# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "trix"
pin "@rails/actiontext", to: "actiontext.esm.js"

# Tiptap Editor
pin "@tiptap/core", to: "https://cdn.jsdelivr.net/npm/@tiptap/core@2.11.5/+esm"
pin "@tiptap/pm/state", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/state/+esm"
pin "@tiptap/pm/view", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/view/+esm"
pin "@tiptap/pm/model", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/model/+esm"
pin "@tiptap/pm/transform", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/transform/+esm"
pin "@tiptap/pm/commands", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/commands/+esm"
pin "@tiptap/pm/schema-list", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/schema-list/+esm"
pin "@tiptap/pm/dropcursor", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/dropcursor/+esm"
pin "@tiptap/pm/gapcursor", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/gapcursor/+esm"
pin "@tiptap/pm/history", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/history/+esm"
pin "@tiptap/pm/keymap", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/keymap/+esm"
pin "@tiptap/pm/inputrules", to: "https://cdn.jsdelivr.net/npm/@tiptap/pm@2.11.5/inputrules/+esm"
pin "@tiptap/starter-kit", to: "https://cdn.jsdelivr.net/npm/@tiptap/starter-kit@2.11.5/+esm"
pin "@tiptap/extension-code-block-lowlight", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-code-block-lowlight@2.11.5/+esm"

# Tiptap内部依存
pin "@tiptap/extension-blockquote", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-blockquote@2.11.5/+esm"
pin "@tiptap/extension-bold", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-bold@2.11.5/+esm"
pin "@tiptap/extension-bullet-list", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-bullet-list@2.11.5/+esm"
pin "@tiptap/extension-code", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-code@2.11.5/+esm"
pin "@tiptap/extension-code-block", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-code-block@2.11.5/+esm"
pin "@tiptap/extension-document", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-document@2.11.5/+esm"
pin "@tiptap/extension-dropcursor", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-dropcursor@2.11.5/+esm"
pin "@tiptap/extension-gapcursor", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-gapcursor@2.11.5/+esm"
pin "@tiptap/extension-hard-break", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-hard-break@2.11.5/+esm"
pin "@tiptap/extension-heading", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-heading@2.11.5/+esm"
pin "@tiptap/extension-history", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-history@2.11.5/+esm"
pin "@tiptap/extension-horizontal-rule", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-horizontal-rule@2.11.5/+esm"
pin "@tiptap/extension-italic", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-italic@2.11.5/+esm"
pin "@tiptap/extension-list-item", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-list-item@2.11.5/+esm"
pin "@tiptap/extension-ordered-list", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-ordered-list@2.11.5/+esm"
pin "@tiptap/extension-paragraph", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-paragraph@2.11.5/+esm"
pin "@tiptap/extension-strike", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-strike@2.11.5/+esm"
pin "@tiptap/extension-text", to: "https://cdn.jsdelivr.net/npm/@tiptap/extension-text@2.11.5/+esm"

# lowlight (コードハイライト)
pin "lowlight", to: "https://cdn.jsdelivr.net/npm/lowlight@3.3.0/+esm"
pin "highlight.js/lib/core", to: "https://cdn.jsdelivr.net/npm/highlight.js@11.11.1/es/core.min.js"
pin "highlight.js/lib/languages/ruby", to: "https://cdn.jsdelivr.net/npm/highlight.js@11.11.1/es/languages/ruby.min.js"
pin "highlight.js/lib/languages/javascript", to: "https://cdn.jsdelivr.net/npm/highlight.js@11.11.1/es/languages/javascript.min.js"
