module Ui
  class TextFieldComponent < ApplicationComponent
    @builder: untyped

    @method: untyped

    @size: untyped

    @variant: untyped

    @html_options: untyped

    SIZE_OPTIONS: ::Array[:full | :large | :medium | :small]

    VARIANT_OPTIONS: ::Array[:default | :alert]

    def initialize: (builder: untyped, method: untyped, size: untyped, ?variant: ::Symbol, **untyped html_options) -> void

    private

    def field_classes: (untyped extra_classes) -> untyped

    def size_class: () -> untyped

    def variant_class: () -> ("" | untyped)
  end
end
