module Page
  module User
    module Confirmations
      class NewPageComponent < ApplicationComponent
        @form: untyped

        @confirmation_path: untyped

        @resource_name: untyped
      end
    end
  end
end
